plugins {
    id 'java'
    id 'application' 
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jar {
    archiveBaseName.set('MyCurseProject')
    manifest {
        attributes 'Main-Class': 'ui.App' 
    }
}

application {
    mainClass = 'ui.App'  
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
}

run {
    standardInput = System.in
}

test {
    useJUnitPlatform()
}